# -*- coding: utf-8 -*-
"""Copy of BMI_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yMPJSJfaQ4PTszkpZbin3FJHVXkHEo-U
"""

print("             BMI CALCULATOR")
print ("------------------------------------------")
print("Calculate your BMI using weight and height.")

while True:
    try:
        weight = float(input("Enter your weight in kg: "))
        height = float(input("Enter your height in metres: "))

        if weight <= 0 or height <= 0:
            print("Error: Weight and height must be greater than zero.")
            continue

        bmi = weight / (height ** 2)

        if bmi < 18.5:
            category = "Underweight"
        elif bmi < 25:
            category = "Normal"
        elif bmi < 30:
            category = "Overweight"
        else:
            category = "Obese"

        print("\nYour BMI:", round(bmi, 2))
        print("Category:", category)

        again = input("\nCalculate again? (yes/no): ").lower()

        if again != "yes":
            print("Thank you for using the BMI Calculator!")
            break

    except ValueError:
        print("Error: Please enter numbers only.")

